version: '3.8'

services:
  isaac-lab:
    image: nvcr.io/nvidia/isaac-lab:2.0.1
    privileged: true
    network_mode: host
    ports:
      - '49100:49100/tcp'  # Livestream
      - '47998:47998/udp'  # Livestream
      - '8888:8888'        # JupyterLab
    environment:
      ACCEPT_EULA: "Y"
    runtime: nvidia
    pull_policy: always
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/ubuntu/docker/isaac-lab/cache/kit:/isaac-sim/kit/cache:rw
      - /home/ubuntu/Launchables/isaac-lab/launch.sh:/workspace/isaaclab/launch.sh
      - /home/ubuntu/Launchables/isaac-lab/livestream_sample.ipynb:/workspace/isaaclab/livestream_sample.ipynb
    user: root
    working_dir: /workspace/isaaclab
    entrypoint: ["/workspace/isaaclab/launch.sh"]
    restart: unless-stopped